Update CI to re-lock

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -90,4 +90,16 @@ jobs:
         key: ${{ runner.os }}-bazel-${{ env.USE_BAZEL_VERSION }}-${{ hashFiles('WORKSPACE', 'repositories.bzl') }}
 
     - name: Run bazel build
-      run: bazelisk build //...
+      run: bazelisk build //... --enable_bzlmod=false
+
+    - name: Run bazel build (bzlmod)
+      run: bazelisk build //... --enable_bzlmod=true
+
+    - name: Check maven_install.json
+      run: |
+        bazelisk run @unpinned_maven//:pin --enable_bzlmod=true
+        if [[ ! -z $(git status --porcelain) ]]; then
+          git status
+          echo "Error Working directory is not clean. Forget to commit generated files?"
+          exit 1
+        fi
